### ISSUE TITLE
error when start  csirtg-smrt

### ISSUE THREAD

**Issue by dionmario** [csirtgadgets/bearded-avenger-deploymentkit#45]
I dont have csirtg support account, I just finished installing cif and when I tried to start csirtg, this is the error that I got : 

cif@brainware:~$ csirtg-smrt

2018-06-27 18:31:11,909 - ERROR - csirtg_smrt.smrt[336] - may need to remove the old cache file: /var/lib/smrt/alexa.com/top-1m.csv.zip
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 331, in _run_smrt
    for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 283, in process
    for indicator_batch in feed_indicators_batches:
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/utils/__init__.py", line 102, in chunk
    for x in it:
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 279, in <genexpr>
    feed_indicators = (i for i in feed_indicators if not self.is_archived_with_log(i))
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 273, in <genexpr>
    feed_indicators = (self.clean_indicator(i, rule) for i in feed_indicators)
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 272, in <genexpr>
    feed_indicators = (i for i in feed_indicators if self.is_valid(i, rule))
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/parser/delim.py", line 20, in process
    for l in self.fetcher.process():
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/fetcher.py", line 293, in process
    from csirtg_smrt.utils.zcontent import get_type
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/utils/zcontent.py", line 6, in <module>
    f = sys.argv[1]
IndexError: list index out of range
2018-06-27 18:31:11,910 - ERROR - csirtg_smrt.smrt[338] - None
Traceback (most recent call last):
  File "/usr/local/bin/csirtg-smrt", line 11, in <module>
    load_entry_point('csirtg-smrt==0.0.0rc2', 'console_scripts', 'csirtg-smrt')()
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 455, in main
    'goback': goback
  File "/usr/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 339, in _run_smrt
    raise e
IndexError: list index out of range

Any idea what is the problem ?

![image](https://user-images.githubusercontent.com/40631457/41971746-b26244d6-7a39-11e8-9251-209d49a1a73e.png)

**Comment by wesyoung** [comment]
couple of things:

+ when you log an issue- please fill out the issue template
+ `csirtg-smrt` should be running as a service (verify with `ps aux` or `sudo journalctl -fu csirtg-*` to verify)
+ if you're trying to figure out how `csirtg-smrt` works, try: `$ csirtg-smrt -d -r /etc/cif/rules/default/openphish.yml` as a start

**Comment by dionmario** [comment]
Thank you for your reply.
Ok, sorry about the issue template, I will fill it now.

# Do you have an active https://csirtg.io/support account ? :)
   No

# Expected behavior and actual behavior.
   expected behavior : no error on start the daemon for the first time
   actual beahvior : error on start the daemon for the first time

# Steps to reporduce the problem
    $ csirtg-smrt
   
# Relevant logs as a result of the actual behavior
    I'll put in a screenshot

# Specifications like the version of the project, operating system, or hardware.
   the version of csirtg is 0.0.0rc2, OS is Ubuntu 16.04, Proc Intel i7 2.7GHz 4 cores, RAM 32GB


"csirtg-smrt should be running as a service (verify with ps aux or sudo journalctl -fu csirtg-* to verify)"
 
![image](https://user-images.githubusercontent.com/40631457/42073584-c6dc9458-7b91-11e8-8e07-d1d8b3fa9858.png)

"if you're trying to figure out how csirtg-smrt works, try: $ csirtg-smrt -d -r /etc/cif/rules/default/openphish.yml as a start"
![1](https://user-images.githubusercontent.com/40631457/42073604-eef2efb4-7b91-11e8-83eb-8e8e98ae91e7.JPG)

Any idea why is that happened ?

**Comment by wesyoung** [comment]
this should be fixed in `csirtg-smrt==1.0.1`
